POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "teste",
    "email": "email@email.com",
    "password": "23432535"
}

###
GET http://localhost:3003/user

###
POST http://localhost:3003/movie/create
Content-Type: application/json

{
    "title": "Lord of the Rings - The Return of the King",
    "description": "The Lord of the Rings: The Return of the King is a 2003 epic fantasy adventure film directed by Peter Jackson, based on the third volume of J. R. R. Tolkien's The Lord of the Rings.",
    "durationInMinutes": 201,
    "yearOfRelease": 2003
}


