###
GET http://localhost:3003/users

###
GET http://localhost:3003/userByType?type=admin

###
GET http://localhost:3003/userByName?name=Coragem

###
POST http://localhost:3003/createUser
Content-Type: application/json

{
    "id": "13",
    "name": "Laura",
    "email": "laura@email.com",
    "type": "ADMIN",
    "age": 32
}