### 
GET http://localhost:3003/ping

###
GET http://localhost:3003/actor/001

###
GET http://localhost:3003/actor?gender=female

###
PUT http://localhost:3003/actor
Content-Type: application/json

{
    "salary": 1000000,
    "id": "005"
}

###
DELETE http://localhost:3003/actor/005