
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Norman Osbourne", 
   "nickname": "Green Goblin", 
   "email": "osbourne2222@oscorp.com" ,
   "password": "ihatepeter"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "osbourne2222@oscorp.com" ,
   "password": "ihatepeter"
}

###
PUT http://localhost:3003/user/edit
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwNzA4M2JkLWZlMWMtNGI3Yy04MzU0LTA5OTczYmM0ZGE3ZCIsImlhdCI6MTY1NTE2MjcwMywiZXhwIjoxNjU1MTY5OTAzfQ.s2jD05Qkh_9VefcaIeX9NpQ0hJamPUs6zLp6eTvFPOQ

{
   "name": "teste",
   "nickname": "teste"
}